create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null default 0,
  correct_answers integer not null default 0,
  total_questions integer not null default 10,
  duration_seconds integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.quiz_results enable row level security;

create policy "Allow public insert quiz results"
on public.quiz_results
for insert
to anon
with check (true);

create policy "Allow public read quiz leaderboard"
on public.quiz_results
for select
to anon
using (true);
