create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null default 0,
  correct_answers integer not null default 0,
  total_questions integer not null default 10,
  duration_seconds integer not null default 0,
  device_id text,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.quiz_results
add column if not exists device_id text,
add column if not exists ip_address text,
add column if not exists user_agent text;

alter table public.quiz_results enable row level security;

drop policy if exists "Allow public insert quiz results" on public.quiz_results;

create policy "Allow public insert quiz results"
on public.quiz_results
for insert
to anon
with check (true);

drop policy if exists "Allow public read quiz leaderboard" on public.quiz_results;

create policy "Allow public read quiz leaderboard"
on public.quiz_results
for select
to anon
using (true);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  player_name text not null,
  device_id text not null unique,
  ip_address text,
  user_agent text,
  started_at timestamptz not null default now()
);

alter table public.quiz_attempts enable row level security;

drop policy if exists "Allow public insert quiz attempts" on public.quiz_attempts;

create policy "Allow public insert quiz attempts"
on public.quiz_attempts
for insert
to anon
with check (true);
